# This file belongs in the config folder, please add it to your /config/configuration.yaml file to enable the UI functionality"""

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
  logs:
    homeassistant.components.cloud: debug

sensor:
  #Open Weather Map - Air Pollution API - Forecast Report
  - platform: rest
    name: "Openweathermap Forecast: Air Pollution"
    scan_interval: 3600
    resource: http://api.openweathermap.org/data/2.5/air_pollution/forecast?lat=56.183038&lon=15.590759&appid=76f843f4e2c57cb1b72d06c1a0fffb95
    value_template: 'OK'
    json_attributes_path: "$.list[0]"
    json_attributes:
      - dt
      - main
      - components
  - platform: template
    sensors:
      openweathermap_forecast_air_pollution_forecast_date:
        friendly_name: "Date"
        unique_id: openweathermap_forecast_air_pollution_forecast_date
        value_template: "{{ state_attr('sensor.openweathermap_forecast_air_pollution', 'dt') | timestamp_custom('%Y-%m-%d') }}"
        device_class: "date"
      openweathermap_forecast_air_quality_index:
        friendly_name: "Air Quality Index"
        unique_id: openweathermap_forecast_air_quality_index
        device_class: "aqi"
        value_template: "{{ state_attr('sensor.openweathermap_forecast_air_pollution', 'main')['aqi'] }}"
      openweathermap_forecast_carbon_monoxide:
        friendly_name: "Carbon Monoxide CO"
        unique_id: openweathermap_forecast_carbon_monoxide
        device_class: "carbon_monoxide"
        unit_of_measurement: 'µg/m³'
        value_template: "{{ '%.2f' | format(state_attr('sensor.openweathermap_forecast_air_pollution', 'components')['co'] / 100) }}"
      openweathermap_forecast_nitrogen_monoxide:
        friendly_name: "Nitrogen Monoxide NO"
        unique_id: openweathermap_forecast_nitrogen_monoxide
        device_class: "nitrogen_monoxide"
        unit_of_measurement: 'µg/m³'
        value_template: "{{ state_attr('sensor.openweathermap_forecast_air_pollution', 'components')['no'] }}"
      openweathermap_forecast_nitrogen_dioxide:
        friendly_name: "Nitrogen Dioxide NO2"
        unique_id: openweathermap_forecast_nitrogen_dioxide
        device_class: "nitrogen_dioxide"
        unit_of_measurement: 'µg/m³'
        value_template: "{{ state_attr('sensor.openweathermap_forecast_air_pollution', 'components')['no2'] }}"
      openweathermap_forecast_ozone:
        friendly_name: "Ozone O3"
        unique_id: openweathermap_forecast_ozone
        device_class: "ozone"
        unit_of_measurement: 'µg/m³'
        value_template: "{{ state_attr('sensor.openweathermap_forecast_air_pollution', 'components')['o3'] }}"
      openweathermap_forecast_sulfur_dioxide:
        friendly_name: "Sulfur Dioxide SO2"
        unique_id: openweathermap_forecast_sulfur_dioxide
        device_class: "sulphur_dioxide"
        unit_of_measurement: 'µg/m³'
        value_template: "{{ state_attr('sensor.openweathermap_forecast_air_pollution', 'components')['so2'] }}"
      openweathermap_forecast_particulate_matter_2_5:
        friendly_name: "PM 2.5"
        unique_id: openweathermap_forecast_particulate_matter_2_5
        device_class: "pm25"
        unit_of_measurement: 'µg/m³'
        value_template: "{{ state_attr('sensor.openweathermap_forecast_air_pollution', 'components')['pm2_5'] }}"
      openweathermap_forecast_particulate_matter_10:
        friendly_name: "PM 10"
        unique_id: openweathermap_forecast_particulate_matter_10
        device_class: "pm10"
        unit_of_measurement: 'µg/m³'
        value_template: "{{ state_attr('sensor.openweathermap_forecast_air_pollution', 'components')['pm10'] }}"
      openweathermap_forecast_ammonia:
        friendly_name: "Ammonia NH3"
        unique_id: openweathermap_forecast_ammonia
        unit_of_measurement: 'µg/m³'
        icon_template: mdi:molecule
        value_template: "{{ state_attr('sensor.openweathermap_forecast_air_pollution', 'components')['nh3'] }}"
